spring:
    datasource:
        driverClassName: org.h2.Driver
        password: sa
        url: jdbc:h2:mem:empdb
        username: admin
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            use-new-id-generator-mappings: false
            ddl-auto: update            
    data:
      mongodb:
        uri: mongodb+srv://<usrname>:<password>@<cluster name>.atwma.mongodb.net/hr?retryWrites=true&w=majority
        database: hr
        
logging:
   level:
      web: DEBUG